general {
    lock_cmd       = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd  = hyprctl dispatch dpms on
}

# dim screen after 4 minutes
listener {
    timeout  = 240
    on-timeout = brightnessctl -s set 10
    on-resume  = brightnessctl -r
}

# lock after 6 minutes
listener {
    timeout  = 360
    on-timeout = loginctl lock-session
}

# turn screen off 30s after lock
listener {
    timeout  = 390
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on
}

# suspend after 20 minutes
listener {
    timeout  = 1200
    on-timeout = systemctl suspend
}
